name: front
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  libsignal_protocol_dart: ^0.5.4
  flutter: 
    sdk: flutter
  adhara_socket_io: ^1.0.1+1
  socket_io_client: ^2.0.0-beta.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

